version: "3.7"

networks:
  datastax:
    name: datastax

volumes:
  dse-cassandra-data:
  dse-studio-notebooks:

services:
  # Reference: https://hub.docker.com/r/datastax/dse-server
  # DataStax Enterprise
  dse:
    image: datastax/dse-server:6.8.1
    container_name: dse
    command: [-s]
    ports:
      - "9042:9042" # cassandra
    environment:
      DS_LICENSE: accept
    volumes:
      - dse-cassandra-data:/var/lib/cassandra
    networks:
      - datastax
    # Allow DSE to lock memory with mlock
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 5G

  # Reference: https://hub.docker.com/r/datastax/dse-studio
  # One instance of DataStax Studio
  studio:
    image: datastax/dse-studio:6.8.1
    container_name: studio
    ports:
      # The Web UI exposed to our host
      - "9091:9091"
    depends_on:
      - dse
    environment:
      DS_LICENSE: accept
    volumes:
      - dse-studio-notebooks:/var/lib/datastax-studio
    networks:
      - datastax
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 2G
